# Версия конфига docker-compose (определяет доступный синтаксис и т.д.)
version: '3'
services:
  nudle-js:
    # Указываем название контейнера
    container_name: nudle-js

    # Создаём образ из Dockerfile
    build:
      # Путь к Dockerfile
      context: ./

      # Dockerfile для создания образа
      dockerfile: Dockerfile

    # Указываем порт на котором будет работать контейнер
    ports:
      - 80:80

    # Подключаем хранилище (Копирование всех файлов текущей рабочей директории в директории по умолчанию для сервера NGINX)
    volumes:
      - .:/usr/share/nginx/html