# Версия конфига docker-compose (определяет доступный синтаксис и т.д.)
version: '3'
services:
  # Название контейнера
  nudle-js:
    # Используется образ NGINX
    image: nginx

    # Порт на котором будет работать контейнер
    ports:
      - 80:80

    # Копирование всех файлов текущей рабочей директории в директории по умолчанию для сервера NGINX
    volumes:
      - .:/usr/share/nginx/html